import { PrismaClient, MacroCategory } from '@prisma/client'
const prisma = new PrismaClient()

const dishes = [
  // Keto
  {
    slug: 'keto-avocado-omelet',
    name: 'Омлет с авокадо',
    description: 'Пышный омлет с ломтиками авокадо и зеленью',
    imageUrl: null,
    macrosPerServing: { calories: 420, protein: 20, fat: 34, carbs: 6, fiber: 4 },
    macroCategory: 'fat',
    dietCompatibility: ['keto'],
    nutritionScore: 78,
  },
  {
    slug: 'keto-salmon-salad',
    name: 'Салат с лососем',
    description: 'Листья салата, авокадо, слабосолёный лосось, оливковое масло',
    imageUrl: null,
    macrosPerServing: { calories: 520, protein: 28, fat: 40, carbs: 8, fiber: 5 },
    macroCategory: 'protein',
    dietCompatibility: ['keto'],
    nutritionScore: 82,
  },
  {
    slug: 'keto-zucchini-pasta',
    name: 'Паста из цукини с песто',
    description: 'Ленты цукини с соусом песто и кедровыми орехами',
    imageUrl: null,
    macrosPerServing: { calories: 360, protein: 12, fat: 30, carbs: 10, fiber: 4 },
    macroCategory: 'fat',
    dietCompatibility: ['keto'],
    nutritionScore: 74,
  },
  {
    slug: 'keto-halloumi-salad',
    name: 'Салат с халлуми и оливками',
    description: 'Салатные листья, сыр халлуми, оливки, оливковое масло',
    imageUrl: null,
    macrosPerServing: { calories: 450, protein: 22, fat: 36, carbs: 6, fiber: 3 },
    macroCategory: 'fat',
    dietCompatibility: ['keto'],
    nutritionScore: 76,
  },
  {
    slug: 'keto-eggs-bacon',
    name: 'Яйца с беконом и зеленью',
    description: 'Яичница, немного бекона, зелень, оливковое масло',
    imageUrl: null,
    macrosPerServing: { calories: 480, protein: 24, fat: 40, carbs: 3, fiber: 0 },
    macroCategory: 'fat',
    dietCompatibility: ['keto'],
    nutritionScore: 70,
  },
  {
    slug: 'keto-shrimp-zoodles',
    name: 'Креветки с лапшой из цукини',
    description: 'Обжаренные креветки, цукини-лапша, чеснок, масло',
    imageUrl: null,
    macrosPerServing: { calories: 390, protein: 28, fat: 24, carbs: 7, fiber: 2 },
    macroCategory: 'protein',
    dietCompatibility: ['keto'],
    nutritionScore: 79,
  },
  {
    slug: 'keto-chia-pudding',
    name: 'Чиа-пудинг на кокосовом молоке',
    description: 'Семена чиа, кокосовое молоко, немного орехов',
    imageUrl: null,
    macrosPerServing: { calories: 350, protein: 10, fat: 26, carbs: 12, fiber: 10 },
    macroCategory: 'fiber',
    dietCompatibility: ['keto'],
    nutritionScore: 73,
  },
  {
    slug: 'keto-eggplant-boats',
    name: 'Баклажаны с сыром и томатами',
    description: 'Запечённые баклажаны, сыр, томаты, базилик',
    imageUrl: null,
    macrosPerServing: { calories: 410, protein: 18, fat: 30, carbs: 11, fiber: 5 },
    macroCategory: 'fat',
    dietCompatibility: ['keto'],
    nutritionScore: 74,
  },

  // High Protein
  {
    slug: 'hp-chicken-bowl',
    name: 'Чикен-боул с киноа',
    description: 'Грудка на гриле, киноа, овощи, йогуртовый соус',
    imageUrl: null,
    macrosPerServing: { calories: 520, protein: 42, fat: 14, carbs: 52, fiber: 7 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 80,
  },
  {
    slug: 'hp-cottage-pancakes',
    name: 'Творожные панкейки',
    description: 'Пышные панкейки из творога с ягодами',
    imageUrl: null,
    macrosPerServing: { calories: 430, protein: 30, fat: 12, carbs: 52, fiber: 4 },
    macroCategory: 'carb',
    dietCompatibility: ['high-protein'],
    nutritionScore: 72,
  },
  {
    slug: 'hp-tuna-salad',
    name: 'Салат с тунцом и фасолью',
    description: 'Тунец, стручковая фасоль, оливковое масло, лимон',
    imageUrl: null,
    macrosPerServing: { calories: 410, protein: 36, fat: 16, carbs: 28, fiber: 6 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 76,
  },
  {
    slug: 'hp-greek-yogurt-bowl',
    name: 'Греческий йогурт с орехами',
    description: 'Густой йогурт, грецкие орехи, немного мёда',
    imageUrl: null,
    macrosPerServing: { calories: 380, protein: 28, fat: 16, carbs: 28, fiber: 2 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 70,
  },
  {
    slug: 'hp-beef-stirfry',
    name: 'Говядина-стирфрай с овощами',
    description: 'Обжаренная говядина, перец, брокколи, соевый соус',
    imageUrl: null,
    macrosPerServing: { calories: 520, protein: 40, fat: 18, carbs: 42, fiber: 6 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 78,
  },
  {
    slug: 'hp-protein-smoothie',
    name: 'Протеиновый смузи с бананом',
    description: 'Сывороточный протеин, банан, молоко/вода, лёд',
    imageUrl: null,
    macrosPerServing: { calories: 320, protein: 32, fat: 4, carbs: 42, fiber: 3 },
    macroCategory: 'carb',
    dietCompatibility: ['high-protein'],
    nutritionScore: 68,
  },
  {
    slug: 'hp-turkey-wrap',
    name: 'Ролл с индейкой и овощами',
    description: 'Тортилья, индейка, салат, томаты, йогуртовый соус',
    imageUrl: null,
    macrosPerServing: { calories: 450, protein: 36, fat: 12, carbs: 48, fiber: 5 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 72,
  },
  {
    slug: 'hp-eggwhite-omelet',
    name: 'Омлет из белков с шпинатом',
    description: 'Белковый омлет, шпинат, томаты, немного сыра',
    imageUrl: null,
    macrosPerServing: { calories: 300, protein: 34, fat: 8, carbs: 18, fiber: 3 },
    macroCategory: 'protein',
    dietCompatibility: ['high-protein'],
    nutritionScore: 74,
  },

  // Low Glycemic
  {
    slug: 'lg-buckwheat-bowl',
    name: 'Гречневый боул с овощами',
    description: 'Гречка, брокколи, шампиньоны, яйца, зелень',
    imageUrl: null,
    macrosPerServing: { calories: 460, protein: 24, fat: 14, carbs: 58, fiber: 10 },
    macroCategory: 'carb',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 79,
  },
  {
    slug: 'lg-oat-chia',
    name: 'Овсянка с чиа и яблоком',
    description: 'Овсяные хлопья, чиа, яблоко, корица',
    imageUrl: null,
    macrosPerServing: { calories: 390, protein: 16, fat: 10, carbs: 58, fiber: 9 },
    macroCategory: 'fiber',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 75,
  },
  {
    slug: 'lg-chicken-stew',
    name: 'Тушёная курица с овощами',
    description: 'Нежная курица с томатами и перцем, минимум масла',
    imageUrl: null,
    macrosPerServing: { calories: 420, protein: 32, fat: 14, carbs: 36, fiber: 6 },
    macroCategory: 'protein',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 77,
  },
  {
    slug: 'lg-lentil-soup',
    name: 'Суп-пюре из чечевицы',
    description: 'Красная чечевица, морковь, томаты, специи',
    imageUrl: null,
    macrosPerServing: { calories: 320, protein: 18, fat: 6, carbs: 46, fiber: 8 },
    macroCategory: 'fiber',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 78,
  },
  {
    slug: 'lg-quinoa-salad',
    name: 'Киноа-салат с огурцом и фетой',
    description: 'Киноа, огурец, фета, зелень, оливковое масло',
    imageUrl: null,
    macrosPerServing: { calories: 430, protein: 18, fat: 14, carbs: 56, fiber: 7 },
    macroCategory: 'carb',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 76,
  },
  {
    slug: 'lg-baked-cod',
    name: 'Запечённая треска с овощами',
    description: 'Филе трески, лимон, брокколи, морковь',
    imageUrl: null,
    macrosPerServing: { calories: 360, protein: 34, fat: 8, carbs: 32, fiber: 5 },
    macroCategory: 'protein',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 80,
  },
  {
    slug: 'lg-ratatouille',
    name: 'Овощное рагу (рататуй)',
    description: 'Баклажан, кабачок, томаты, перец, травы',
    imageUrl: null,
    macrosPerServing: { calories: 240, protein: 8, fat: 8, carbs: 34, fiber: 8 },
    macroCategory: 'fiber',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 79,
  },
  {
    slug: 'lg-cottage-berries',
    name: 'Творог с ягодами и орехами',
    description: 'Нежирный творог, ягоды, немного орехов',
    imageUrl: null,
    macrosPerServing: { calories: 310, protein: 26, fat: 10, carbs: 28, fiber: 4 },
    macroCategory: 'protein',
    dietCompatibility: ['low-glycemic'],
    nutritionScore: 73,
  },
]

async function main() {
  for (const d of dishes) {
    await prisma.dish.upsert({
      where: { slug: d.slug },
      update: {
        name: d.name,
        description: d.description,
        imageUrl: d.imageUrl,
        macrosPerServing: d.macrosPerServing as any,
        macroCategory: d.macroCategory as any,
        dietCompatibility: d.dietCompatibility as any,
        nutritionScore: d.nutritionScore,
      },
      create: {
        slug: d.slug,
        name: d.name,
        description: d.description,
        imageUrl: d.imageUrl,
        macrosPerServing: d.macrosPerServing as any,
        macroCategory: d.macroCategory as any,
        dietCompatibility: d.dietCompatibility as any,
        nutritionScore: d.nutritionScore,
      },
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })


